#!/bin/bash
if [ "$MERCURIAL_REPO_URL" == "" ];
then
    echo "Mercurial repository URL not defined"
    exit 1
fi
if [ "$GIT_REPO_URL" == "" ];
then
    echo "Git repository URL not defined"
    exit 1
fi

branchCount=0
while [ true ];
do
    nextBranchNumber=$((branchCount+1))

    mercurialBranchName="MERCURIAL_BRANCH_NAME_$nextBranchNumber"
    mercurialBranch=${!mercurialBranchName}
    if [ "$mercurialBranch" == "" ];
    then
        break
    fi

    gitBranchName="GIT_BRANCH_NAME_$nextBranchNumber"
    gitBranch=${!gitBranchName}
    if [ "$gitBranch" == "" ];
    then
        break
    fi

    branchCount=$nextBranchNumber
done

if [ $branchCount -le 0 ];
then
    exit 1
fi

cd ~
hg clone $MERCURIAL_REPO_URL repository
if [ $? -ne 0 ];
then
    echo "Mercurial repository clone failed"
    exit 1
fi
cd ~/repository

for (( branchIndex=1; branchIndex<=$branchCount; branchIndex++ ));
do
    mercurialBranchName="MERCURIAL_BRANCH_NAME_$branchIndex"
    mercurialBranch="${!mercurialBranchName}"

    gitBranchName="GIT_BRANCH_NAME_$branchIndex"
    gitBranch="${!gitBranchName}"

    if [ "$mercurialBranch" != "" ] && [ "$gitBranch" != "" ];
    then
        if [ "$gitBranch" == "$mercurialBranch" ];
        then
            hg bookmark -r "$mercurialBranch" "git-$mercurialBranch"
        else
            hg bookmark -r "$mercurialBranch" "$gitBranch"
        fi
    fi
done

hg gexport

for (( branchIndex=1; branchIndex<=$branchCount; branchIndex++ ));
do
    mercurialBranchName="MERCURIAL_BRANCH_NAME_$branchIndex"
    mercurialBranch="${!mercurialBranchName}"

    gitBranchName="GIT_BRANCH_NAME_$branchIndex"
    gitBranch="${!gitBranchName}"

    if [ "$mercurialBranch" != "" ] && [ "$gitBranch" != "" ];
    then
        if [ "$gitBranch" == "$mercurialBranch" ];
        then
            git branch -m "git-$mercurialBranch" "$gitBranch"
        fi
        git push -u $GIT_REPO_URL "$gitBranch"
    fi
done
