#!/bin/bash
if [ "$MERCURIAL_REPO_URL" == "" ];
then
    echo "Mercurial repository URL not defined"
    exit 1
fi
if [ "$GIT_REPO_URL" == "" ];
then
    echo "Git repository URL not defined"
    exit 1
fi

maxBranchNumber=0
hasBranches=0
emptyBranchNumberCount=0
maxEmptyBranchNumberCount=100
while [ true ];
do
    maxBranchNumber=$((maxBranchNumber+1))

    mercurialBranchName="MERCURIAL_BRANCH_NAME_$maxBranchNumber"
    mercurialBranch=${!mercurialBranchName}

    if [ "$mercurialBranch" == "" ];
    then
        emptyBranchNumberCount=$((emptyBranchNumberCount+1))
        if [ $emptyBranchNumberCount -ge $maxEmptyBranchNumberCount ];
        then
            break
        fi
    else
        hasBranches=1
        emptyBranchNumberCount=0
    fi
done

if [ $hasBranches -ne 1 ];
then
    echo "No branches defined"
    exit 1
fi
echo "Maximum branch number: $maxBranchNumber"

cd ~
hg clone $MERCURIAL_REPO_URL repository
if [ $? -ne 0 ];
then
    echo "Mercurial repository clone failed"
    exit 1
fi
cd ~/repository

for (( branchIndex=1; branchIndex<=$maxBranchNumber; branchIndex++ ));
do
    mercurialBranchName="MERCURIAL_BRANCH_NAME_$branchIndex"
    mercurialBranch="${!mercurialBranchName}"

    gitBranchName="GIT_BRANCH_NAME_$branchIndex"
    gitBranch="${!gitBranchName}"
    if [ "$gitBranch" == "" ];
    then
        gitBranch=$mercurialBranch
    fi

    if [ "$mercurialBranch" != "" ];
    then
        echo "Create bookmark: $mercurialBranch -> $gitBranch"
        if [ "$gitBranch" == "$mercurialBranch" ];
        then
            hg bookmark -r "$mercurialBranch" "git-$mercurialBranch"
        else
            hg bookmark -r "$mercurialBranch" "$gitBranch"
        fi
    fi
done

hg gexport

for (( branchIndex=1; branchIndex<=$maxBranchNumber; branchIndex++ ));
do
    mercurialBranchName="MERCURIAL_BRANCH_NAME_$branchIndex"
    mercurialBranch="${!mercurialBranchName}"

    gitBranchName="GIT_BRANCH_NAME_$branchIndex"
    gitBranch="${!gitBranchName}"
    if [ "$gitBranch" == "" ];
    then
        gitBranch=$mercurialBranch
    fi

    if [ "$mercurialBranch" != "" ];
    then
        if [ "$gitBranch" == "$mercurialBranch" ];
        then
            git branch -m "git-$mercurialBranch" "$gitBranch"
        fi
        echo "Push git branch $gitBranch"
        git push -u $GIT_REPO_URL "$gitBranch"
    fi
done
